services:
  - type: web
    name: kaka-server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm --workspace server run start
    envVars:
      - key: PORT
        value: 10000
      - key: CLIENT_ORIGIN
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
